### ISSUE TITLE
./configure: line 3004: syntax error near unexpected token `2.2.6'

### ISSUE THREAD

**Issue by helen-fornazier** [ClusterLabs/fence-agents#158]
Should I run ./autogen.sh with any kind of argument?

    koike@fence-debian9-1:~/fence-agents$ ./autogen.sh
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal -I make -I m4
    configure.ac:70: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    ../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    ../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
    ../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
    configure.ac:70: the top level
    configure.ac:70: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    ../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    ../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
    ../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
    configure.ac:70: the top level
    autoreconf: configure.ac: tracing
    configure.ac:70: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    ../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    ../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
    ../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
    configure.ac:70: the top level
    autoreconf: configure.ac: not using Libtool
    autoreconf: running: /usr/bin/autoconf --include=make
    configure.ac:70: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    ../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    ../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
    ../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
    configure.ac:70: the top level
    autoreconf: running: /usr/bin/autoheader --include=make
    configure.ac:70: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    ../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    ../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
    ../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
    configure.ac:70: the top level
    autoreconf: running: automake --add-missing --copy --no-force
    configure.ac:70: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    ../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    ../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
    ../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
    configure.ac:70: the top level
    configure.ac:54: installing './compile'
    configure.ac:18: installing './config.guess'
    configure.ac:18: installing './config.sub'
    configure.ac:9: installing './install-sh'
    configure.ac:9: installing './missing'
    fence/agents/Makefile.am: installing './depcomp'
    autoreconf: Leaving directory `.'
    Now run ./configure and make
    koike@fence-debian9-1:~/fence-agents$ ./configure
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    ./configure: line 3004: syntax error near unexpected token `2.2.6'
    ./configure: line 3004: `LT_PREREQ(2.2.6)'

**Comment by marxsk** [comment]
No, it should work without any option.

Can you tell us more about version of automake/autoconf/ ... and distribution?

**Comment by helen-fornazier** [comment]
koike@fence-debian9-1:~/fence-agents$ apt policy automake
    automake:
      Installed: 1:1.15-6
      Candidate: 1:1.15-6
      Version table:
     *** 1:1.15-6 500
            500 http://deb.debian.org/debian stretch/main amd64 Packages
            100 /var/lib/dpkg/status
    koike@fence-debian9-1:~/fence-agents$ apt policy autoconf
    autoconf:
      Installed: 2.69-10
      Candidate: 2.69-10
      Version table:
     *** 2.69-10 500
            500 http://deb.debian.org/debian stretch/main amd64 Packages
            100 /var/lib/dpkg/status
    koike@fence-debian9-1:~/fence-agents$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 9.2 (stretch)
    Release:        9.2
    Codename:       stretch

**Comment by marxsk** [comment]
Please add also libtool version; your automake/autoconf looks valid.

thanks

**Comment by helen-fornazier** [comment]
Problem solved, libtool wasn't installed, thanks for your help, sorry for the noise.

**Comment by dipika21** [comment]
libtool is installed, but facing same issue :(
