### ISSUE TITLE
Question: fabrics and network fencing

### ISSUE THREAD

**Issue by helen-fornazier** [ClusterLabs/fence-agents#160]
(please, let me know if this isn't the right place to post questions, I am new to the community)
Hi,
The README.md defines power, networking and configuration fencing devices, I also see in some parts of the code the option "fabric_fencing", but in the actions there are defined are on, off, reboot, status, list, and monitor.
Then it seems that only power fencing is supported, is this correct? Or maybe I am not understanding the right way to write a fabric or networking fencing within the project ? I would appreciate any pointers

Thanks

**Comment by marxsk** [comment]
The best way to ask a question is either users@clusterlabs.org or stackoverflow. 

But in general, we support all three of those types. We do not have any 'network' fence agents but we have several 'fabric' fence agents and they are heavily used (e.g. fence_scsi). The main difference is that fabric fence agent do not power off the machine and they have to be unfenced (=registered) before they can be fenced.
