### ISSUE TITLE
[RFE] fence-agents could use some porting attention (FreeBSD)

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/fence-agents#179]
Already told e-ddie on IRC, but just for the record, fence-agents fails to build on FreeBSD.

./autogen.sh 
./configure PYTHON=python3.6 MAKE=gmake

the first issue appears to be in configure itself:

15:43:08 checking for strtol... yes
15:43:08 find: -printf: unknown primary or operator
15:43:08 checking for python version... 3.6

the find implementation on FreeBSD does not understand %P.

There are several errors during the build, probably caused by generated bashisms. bash is not default shell on many system and we should probably not assume it´s even installed.

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/fence-agents/pull/185

**Comment by oalbrigt** [comment]
The fixes for FreeBSD has been merged.
