### ISSUE TITLE
The change of the pass is necessary.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#18]
In the next version of docker, path name is different.
 * Docker 1.7.1

In Docker 1.7.1, it becomes v1.12.

(snip)
def send_cmd(options, cmd, post = False):
	url = "http%s://%s:%s/v1.11/%s" % ("s" if "--ssl" in options else "", options["--ip"], options["--ipport"], cmd)
(snip)

The pass of fence_docker seems to have to be a parameter to support Docker of the new version.

Best Regards,
Hideo Yamauch.

**Comment by marxsk** [comment]
Hi,

I'm thinking about adding --api-version (api-version) with default to 1.11. Does it makes sense to you?

**Comment by HideoYamauchi** [comment]
Hi,

That sounds nice.
I agree to you, too.

Many thanks!
Hideo Yamauchi.

**Comment by marxsk** [comment]
Patches are imported. Please, retest upstream. I don't have docker installed right now.

**Comment by HideoYamauchi** [comment]
Okay!
I will test it next week.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi,

I confirmed your correction.

------------------------------------------------
[root@sl71-docker ~]# fence_docker --help
Usage:
	fence_docker [options]
(snip)
   --api-version                  Version of Docker Remote API (default: 1.11)
(snip)
[root@sl71-docker ~]# fence_docker -o status -a 127.0.0.1 -u 4243 -n test2 --api-version 1^C
[root@sl71-docker ~]# vi /usr/sbin/fence_docker 
[root@sl71-docker ~]# fence_docker -o status -a 127.0.0.1 -u 4243 -n test2 --api-version 1.12
Status: ON
[root@sl71-docker ~]# fence_docker -o off -a 127.0.0.1 -u 4243 -n test2 --api-version 1.12
Success: Powered OFF

[root@sl71-docker ~]# fence_docker -o on -a 127.0.0.1 -u 4243 -n test2 --api-version 1.12
Cannot parse json
Success: Powered ON
[root@sl71-docker ~]# fence_docker -o reboot  -a 127.0.0.1 -u 4243 -n test2 --api-version 1.12
Cannot parse json
Success: Rebooted

------------------------------------------------

The next problem seems to still remain.
In on and reboot, "Cannot parse json" rises.
The message is given, but on and reboot seem to move well.

I think that the correction corresponding to this message is necessary.

Best Regards,
Hideo Yamauchi.
