### ISSUE TITLE
fence_vmware_soap doesn't work with >= Python 2.7.9

### ISSUE THREAD

**Issue by miff2000** [ClusterLabs/fence-agents#184]
It appears that on systems with Python version 2.7.9 and beyond the `vmware_fence_soap`  script fails with the following:  

```
root@server:~# fence_vmware_soap -a 172.16.30.232 -l vmware_fence_user -p secure_pass --ssl-insecure -z -o list
Unable to connect/login to fencing device
```

This is seen on Ubuntu 16.04 running Python 2.7.12 out of the box, whereas CentOS 7 running Python 2.7.5 doesn't have this issue.  

Hacky changes can be made to fence_vmware_soap to fix it, adding in the following near the top  
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

This yields InsecureRequestWarning alerts still, which can also be overridden using
```
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

This appears to be related to HTTPS Hostname verification being added in Python 2.7.9 (https://docs.python.org/2/library/httplib.html#httplib.HTTPSConnection)

**Comment by oalbrigt** [comment]
This has already been fixed, so you'll have to report the issue to your distribution, and point them to https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/vmware_soap/fence_vmware_soap.py#L38-L46.
