### ISSUE TITLE
How to run agent during development?

### ISSUE THREAD

**Issue by cymen** [ClusterLabs/fence-agents#201]
So I'm reading this:

https://docs.pagure.org/ClusterLabs.fence-agents/FenceAgentAPI.md

All making sense however if I try to run my agent (or say the AWS agent) directly via Python, I get:

```
~/fence-agents# python agents/aws/fence_aws.py
Traceback (most recent call last):
  File "agents/aws/fence_aws.py", line 7, in <module>
    from fencing import *
ImportError: No module named fencing
```

I unblocked myself by adding another `sys.path.append` call pointing to my local `fence-agents/lib` directory. First I tried setting an env variable `FENCEAGENTSLIBDIR` but that didn't work (so no clue what `sys.path.append("@FENCEAGENTSLIBDIR@")` is doing -- rarely use Python).

It would be great if there was a brief overview of the workflow of developing an agent. Particularly, how to get around the above issue. When do I need to build? Etc. I think I'm unblocked but at the very least opening this for the next person in my shoes.

**Comment by cymen** [comment]
Oh, and if it can be explained here, I'm happy to do a PR with doc update.

Also the URL at bottom of FenceAgentAPI.md is bad for the metadata.rng.

**Comment by oalbrigt** [comment]
@FENCEAGENTSLIBDIR@ gets replaced in the agents files when you run "./autogen.sh && ./configure && make". After doing that you can run e.g. "PYTHONPATH=lib agents/aws/fence_aws -h".

**Comment by cymen** [comment]
Ah, that is a bit unfortunate that there is a compile step. If anyone else comes along, I found it was easier to just put a temporary `sys.path.append("/path/to/fence-agents/lib")` as I could just run directly then without a compile.
