### ISSUE TITLE
fence_scsi: not Python3 safe

### ISSUE THREAD

**Issue by bootc** [ClusterLabs/fence-agents#206]
Using `fence_scsi` with python3 as the interpreter leads to errors like this:

```2018-05-22 14:44:19,110 INFO: Executing: /usr/sbin/corosync-cmapctl totem.cluster_name
2018-05-22 14:44:19,118 DEBUG: 0 totem.cluster_name (str) = zfs
Traceback (most recent call last):
  File "/usr/sbin/fence_scsi", line 512, in <module>
    main()
  File "/usr/sbin/fence_scsi", line 489, in main
    options["--key"] = generate_key(options)
  File "/usr/sbin/fence_scsi", line 199, in generate_key
    return "%.4s%.4d" % (get_cluster_id(options), int(get_node_id(options)))
  File "/usr/sbin/fence_scsi", line 184, in get_cluster_id
    return hashlib.md5(match.group(1)).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by oalbrigt** [comment]
What version of fence-agents are you running?

**Comment by bootc** [comment]
This was using Debian's 4.2.0-1. I've also reported the bug there: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899310

**Comment by oalbrigt** [comment]
Can you update "match.group(1)" to "match.group(1).encode()" and see if that solves the issue for you?

**Comment by bootc** [comment]
Yes the patch on the Debian bug does that and appears to fix it:
https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=899310;filename=fence_scsi.patch;msg=15

**Comment by oalbrigt** [comment]
Thanks. I've applied that patch in this PR: https://github.com/ClusterLabs/fence-agents/pull/208

**Comment by oalbrigt** [comment]
Adding your patch for reference, as I closed mine: https://github.com/ClusterLabs/fence-agents/pull/207
