### ISSUE TITLE
fence_rhevm is working only for admin 

### ISSUE THREAD

**Issue by emesika** [ClusterLabs/fence-agents#222]
fence_rhevm script is sending start/stop REST API calls (vms/<uuid>/<action>)
One of the parameters that fence_rhevm takes is the plug parameter that is actually the VM name as it known by RHEV 
In order to construct a  REST API call , fence_rhevm issues a search call via the API in order to find the VM UUID given its name 
But, if the user is not an admin this call will return an empty result since search can be used only by admin user.
So, what we get here is a situation in which a user that owns the VM can not access it via the fence_rhevm script 

A possible solution to this problem may be getting rid from the search request , sending a GET REST API call to get all user VMs and then analyzing the result in order to get the requested VM UUID

**Comment by Klaas-** [comment]
I think this is fixed, at least we use fencing without an admin user

**Comment by oalbrigt** [comment]
This has been fixed. Closing issue.
