### ISSUE TITLE
Redfish based fence agent

### ISSUE THREAD

**Issue by Klaas-** [ClusterLabs/fence-agents#230]
Hi,
are there any plans to do a [redfish](https://www.dmtf.org/standards/redfish) based fence agent? This could help to consolidate a lot of the new remote management cards.

Greetings
Klaas

**Comment by oalbrigt** [comment]
We are planning to do a Redfish based fence agent, and are currently working on getting hardware for testing.

**Comment by Klaas-** [comment]
I think you can do some basic testing against https://github.com/DMTF/Redfish-Profile-Simulator

**Comment by jose-delarosa** [comment]
Happy to help and collaborate. Any news?

**Comment by Klaas-** [comment]
fixed through #253
