### ISSUE TITLE
Fence vmware Soap Problem

### ISSUE THREAD

**Issue by lfratini** [ClusterLabs/fence-agents#243]
Environment : 2 VM linux CentOS 7.5.1804 
pcs-0.9.162-5.el7.centos.1.x86_64
fence-agents-common-4.0.11-86.el7_5.3.x86_64
fence-agents-vmware-soap-4.0.11-86.el7_5.3.x86_64

pcs status log this error 

WARNING: following stonith devices have the 'action' option set, it is recommended to set 'pcmk_off_action'

And the log show this error

Oct  9 12:54:08 XXX  stonith-ng[2302]: warning: fence_vmware_soap[1563] stderr: [ Failed: Unable to obtain correct plug status or plug is not available ]

**Comment by oalbrigt** [comment]
Can you show the output of `pcs stonith show --full`?

**Comment by lfratini** [comment]
Resource: vmfence (class=stonith type=fence_vmware_soap)
  Attributes: ipaddr=192.168.X.X login=xxx passwd=xxxx pcmk_host_map="XXXX:42320202-bd84-24aa-cd4e-e3fa0a4ed22d XXXX:4232999e-b42f-7c1e-3c0d-cd8201764e5b" ssl=1 ssl_insecure=1 pcmk_monitor_timeout=240s
  Operations: monitor interval=60s (vmfence-monitor-interval-60s)

**Comment by oalbrigt** [comment]
I think you need to separate `pcmk_host_map` entries with `;` or `,`. I've requested a better example for this in future pcs versions.

I'm not sure what causes the action error, but maybe it's just a side-effect of using incorrect separator in the `pcmk_host_map` parameter.

**Comment by lfratini** [comment]
Ok thanks I did not find this on documentation . I wil try

**Comment by lfratini** [comment]
Ok I removed the vmfence resource, and i created the resource with entries separated by , as you said . 
For one week , monitoring the fence resource , all is ok the error disappeared .

Thanks
