### ISSUE TITLE
[Feature] fence_openstack - use an openrc file

### ISSUE THREAD

**Issue by mgrzybek** [ClusterLabs/fence-agents#262]
For instance, `fence_openstack` requires some options to run correctly, for example `--auth-url` or `--project-domain-name`. However these parameters are usually written into an openrc file used to export `OS_*` variables.

We should be able to use an option called `--openrc-file` to get the pieces of information we need thanks to environment variables.

**Comment by oalbrigt** [comment]
Makes sense. Hopefully the API supports simply providing the openrc-file so we can just hand it off without adding any code to read the file in the agent.

If not you might look in fence_scsi's way of reading variables from /etc/sysconfig/stonith:
https://github.com/ClusterLabs/fence-agents/blob/master/agents/scsi/fence_scsi.py#L374

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/fence-agents/pull/465 / https://github.com/ClusterLabs/fence-agents/pull/466
