### ISSUE TITLE
[Enhancement] fence_scsi - Correspondence to new node name specification method.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#270]
Hi All,

The following setup command line is available from RHEL8.

 - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.0_release_notes/new-features#high-availability-clusters

```
 pcs cluster setup my_cluster rh80-01 addr=192.168.106.183 addr=192.168.107.183  rh80-2 addr=192.168.106.184 addr=192.168.107.184

```

In this case, the corosync.conf nodelist is generated as follows.

```
(snip)
nodelist {
    node {
        ring0_addr: 192.168.106.183
        ring1_addr: 192.168.107.183
        name: rh80-01
        nodeid: 1
    }

    node {
        ring0_addr: 192.168.106.184
        ring1_addr: 192.168.107.184
        name: rh80-02
        nodeid: 2
    }
}
(snip)
```

At this time, nodelist returned by corosyc-cmapctl is as follows.
```
[root@rh80-01 ~]# corosync-cmapctl nodelist
nodelist.local_node_pos (u32) = 0
nodelist.node.0.name (str) = rh80-01
nodelist.node.0.nodeid (u32) = 1
nodelist.node.0.ring0_addr (str) = 192.168.106.183
nodelist.node.0.ring1_addr (str) = 192.168.107.183
nodelist.node.1.name (str) = rh80-02
nodelist.node.1.nodeid (u32) = 2
nodelist.node.1.ring0_addr (str) = 192.168.106.184
nodelist.node.1.ring1_addr (str) = 192.168.107.184
```

If you set the fence_scsi resource with the following command, get_node_id() will fail.

```
pcs stonith create prmStonithScsi fence_scsi pcmk_host_list="rh80-01 rh80-02" pcmk_reboot_action="off" devices="/dev/sdb" meta provides="unfencing" --force

```

This is because fence_scsi does not correspond to the designation of the node name at the time of cluster setup with new pcs.

```
def get_node_id(options):
        cmd = options["--corosync-cmap-path"] + " nodelist"

        match = re.search(r".(\d+).ring._addr \(str\) = " + options["--plug"] + "\n", run_cmd(options, cmd)["out"])
        return match.group(1) if match else fail_usage("Failed: unable to parse output of corosync-cmapctl or node does not exist")
```

If matching to nodelist.node.X.ringX_addr fails, it is necessary to match to nodelist.node.X.name.

```
re.search(r".(\d+).name \(str\) = " + options["--plug"] + "\n", run_cmd(options, cmd)["out"])

```

I need to fix it. 
The setup of fence_scsi fails when using the new pcs cluster specification in RHEL8 environment.

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Thanks. I've created https://github.com/ClusterLabs/fence-agents/pull/273 to search using the new specification and fallback to the old specification in case it doesnt match before failing.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Great!

I will test your fix tomorrow.
I will inform the result.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

I confirmed the improvement of the problem with RHEL7 and RHEL8 running different pcs versions.
Your fix solved the this problem.

Please merge the fix.

Many thanks,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Thanks for testing. I've merged the patch.

**Comment by HideoYamauchi** [comment]
Thanks!
