### ISSUE TITLE
[Question] About multiple device specification of fence_scsi.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#278]
Hi All,

We are checking control using fence_scsi.

With fence_scsi, multiple devices can be specified as parameters.

```
# pcs stonith create prmStonithScsi fence_scsi pcmk_host_list="rh80-01 rh80-02" pcmk_reboot_action="off" devices="/dev/sdb,/dev/sdc,/dev/sdd" meta provides="unfencing" --force

```

However, when multiple devices are actually specified as parameters, inconsistency of reservation keys from split brain may occur.

```
The key of each node is as follows
 nodeA - 0x5e2a0000
 nodeB - 0x5e2a0001

After split brain occurs, each device is reserved as follows.

[root@rh80-01 ~]# sg_persist -i -n -k -d /dev/sdb
  PR generation=0x6a1, 4 registered reservation keys follow:
    0x5e2a0001
    0x5e2a0001
    0x5e2a0001
    0x5e2a0001
[root@rh80-01 ~]# sg_persist -i -n -k -d /dev/sdc
  PR generation=0x54, 4 registered reservation keys follow:
    0x5e2a0001
    0x5e2a0001
    0x5e2a0001
    0x5e2a0001
[root@rh80-01 ~]# sg_persist -i -n -k -d /dev/sdd
  PR generation=0x54, 4 registered reservation keys follow:
    0x5e2a0000
    0x5e2a0000
    0x5e2a0000
    0x5e2a0000

```

As a result, detection and restart of the watchdog service fail(fence_scsi_check_hardreboot), causing a service outage.

If you specify multiple devices, what cluster configuration do you assume?
In order to avoid this problem, is it necessary to set the delay parameter of fence_scsi to ensure that either node takes a reservation?

Best Regards,
Hideo Yamauchi.

**Comment by marxsk** [comment]
@HideoYamauchi the situation that you explained makes sense. Both of the nodes attempt to fence each other, so delay option should help. The other option is to add the third item that can be used for selecting the "correct" cluster (3rd node, quorum disk, ...).

**Comment by HideoYamauchi** [comment]
Hi Marek,

Thanks for your comment.
All right!

Thanks,
Hideo Yamauchi.
