### ISSUE TITLE
fence_vmware_rest: monitor issue with more than 1000 VMs

### ISSUE THREAD

**Issue by hugeps** [ClusterLabs/fence-agents#280]
In relation to the known BUG https://access.redhat.com/solutions/3718421
Caused by this code:
https://github.com/ClusterLabs/fence-agents/blob/22e716dd2feeafd6b698622404ba181ecc12d3c4/agents/vmware_rest/fence_vmware_rest.py#L36

Proposed solution:
It makes more sense to supply the filter parameters as described here
http://vmware.github.io/vsphere-automation-sdk-rest/6.7.1/operations/com/vmware/vcenter/vm.list-operation.html

Need to convert list of VM names into   "vcenter/vm?filter.names.1=vm1&filter.names.2=vm2&....

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/fence-agents/pull/330

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/fence-agents/pull/333
