### ISSUE TITLE
[Enhancement] The fence_scsi watchdog script can cause mount error.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#284]
Hi All,

We configured the cluster using fence_scsi in the pacemaker cluster.
As recommended by RHEL, it also uses the watchdog service and fence_scsi_check_hardreboot.

An error may occur when mounting a partition managed by fence_scsi by Filesystem RA with start.
We received a conclusion from RHEL that this is because the sg_persist command executed from the script executed by the watchdog service makes the mount target invisible for a moment.

This situation can be easily reproduced by executing the following two scripts simultaneously.
(In the following example, the device name is /dev/msa_b.)

If you run the script at the same time, mount sometimes fails.

1. Script1.

```
#!/bin/sh
for i in {1..1000}; do
echo "### ${i} ###"

mount /dev/msa_b1 /dbfp/pgdata
if [ $? -ne 0 ]; then
    break
fi
sleep 2
umount /dev/msa_b1
sleep 2

done;
```

2. Script2.

```
#!/bin/sh
for i in {1..10000}; do
echo "### ${i} ###"
sg_persist -n -i -k -d /dev/msa_b
sleep 1
done;
````

Is it possible to change the sg_persist command executed from fence_scsi(scsi_check) to something to avoid this mounting error?
Or is it difficult to change that?

(I tried to confirm the same with fnc_mpath (mpathpersist), but mpathpersist did not seem to have a problem.)

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
This functionality has been ported to the fence_mpath, which should solve issues seen with sg_persist.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment.

Really...
I will look at the processing of fence_mpath.


Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

I tried comparing fence_mpath and fence_scsi, but I couldn't find any special parts that correspond to the problem with fence_mpath.

Do you know where fence_mpath addresses the problem?

Maybe the mpthpersist command supported?

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Correct.

fence_mpath uses mpathpersist, which doesnt have the issues we've seen with the sg_persist/sg_turs commands used in fence_scsi.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment.

I am a little confused with your answers.

I don't understand the difference between the detailed processing of mpathpersist and sg_persist, but I think that this problem can be summarized as follows.

1) The same problem does not occur in fence_mpath. Alternatively, the mpathpersist command can avoid this problem.
2) This problem occurs in fence_scsi. Since fence_scsi can only use sg_persist to obtain keys, this problem cannot be avoided at present. In order to avoid the problem, it is necessary to deal with the problem with sg_persist.

What do you think?


Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
There's also an option to use the `retry=1` or higher and `retry-sleep` in `/etc/sysconfig/stonith` for fence_scsi if your distro has a newer fence_scsi version to work around the issue.

https://github.com/ClusterLabs/fence-agents/blob/master/agents/scsi/fence_scsi.py#L403

Optimally the issue would be fixed in sg_persist.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment.

When a problem occurs, it is the mount command that causes the error, so I don't think that retrying with fence_scsi will solve the problem.

I tried to comment on whether the sg_persist issue could be fixed.

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
You'll have to make an issue on the sg_persist repository for them to improve the way it works.

The mpath tools either request the info in a better way from the kernel, or has some built-in retry-mechanic in cases where sg_persist would fail.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment.

All right!

Many thanks,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
You're welcome.
