### ISSUE TITLE
[Question] About fence_mpath settings.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#285]
Hi All,

There was not much information on how to set fence_mpath.

We tried the following configuration as with other stonith plug-ins.
The nodes that make up the cluster are two RHEL8 nodes.

```
pcs stonith create prmStonithMpath1 fence_mpath pcmk_on_timeout="70" pcmk_off_timeout="70" pcmk_host_list="rh80-03 rh80-04" pcmk_monitor_action="metadata" \
pcmk_reboot_action="off" key=123abc devices="/dev/mapper/lun4" power_wait="65" meta provides="unfencing"

pcs stonith create prmStonithMpath2 fence_mpath pcmk_on_timeout="70" pcmk_off_timeout="70" pcmk_host_list="rh80-03 rh80-04" pcmk_monitor_action="metadata" \
pcmk_reboot_action="off" key=456abc devices="/dev/mapper/lun4" power_wait="65" meta provides="unfencing"
(snip)
pcs constraint location prmStonithMpath1 prefers rh80-03=-INFINITY
pcs constraint location prmStonithMpath2 prefers rh80-04=-INFINITY
(snip)
```

However, with this setting, it was not possible to register each other's keys successfully on the device.

```
[root@rh80-03 ~]# mpathpersist -i -k -d /dev/mapper/lun4
  PR generation=0xbf,   2 registered reservation keys follow:
    0x123abc
    0x123abc
```

Based on the setting information of fence_mpath of RHEL, we changed to the following setting.
The location constraint has also been discarded.
 * https://access.redhat.com/solutions/2766611

```
pcs stonith create prmStonithMpath1 fence_mpath pcmk_on_timeout="70" pcmk_off_timeout="70" pcmk_host_list="rh80-03" pcmk_monitor_action="metadata" \
pcmk_reboot_action="off" key=123abc devices="/dev/mapper/lun4" power_wait="65" meta provides="unfencing"

pcs stonith create prmStonithMpath2 fence_mpath pcmk_on_timeout="70" pcmk_off_timeout="70" pcmk_host_list="rh80-04" pcmk_monitor_action="metadata" \
pcmk_reboot_action="off" key=456abc devices="/dev/mapper/lun4" power_wait="65" meta provides="unfencing"

```

Registered each other's key in the device and was able to work correctly.
```
[root@rh80-03 ~]# mpathpersist -i -k -d /dev/mapper/lun4
  PR generation=0x10c,  4 registered reservation keys follow:
    0x123abc
    0x123abc
    0x456abc
    0x456abc
```

Compared to fence_scsi, fence_mpath seems to be a little difficult to set up.

From the configuration information of RHEL and actual operation, we think that the fence_mpath setting is the following specification, but is our understanding correct?

1. Only one node with each key is set in pcmk_host_list.
2. Do not write location constraints for fence_mpath resources

Best Regards,
Hiedeo Yamauchi.

**Comment by oalbrigt** [comment]
That looks good to me.

location constraints doesnt work for fence devices, which is why you need to use pcmk_host_list instead.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment.
I understood that the fence_mpath setting is different from fence_scsi.

I think it would be nice to have a document that shows the differences in the settings around here.

This issue will close.

Man thanks,
Hideo Yamauchi.
