### ISSUE TITLE
"fence_pve" cannot import name run_delay

### ISSUE THREAD

**Issue by xtavras** [ClusterLabs/fence-agents#29]
Hi,

I'm trying to test stonith on proxmox with "fence_pve" agent, unfortunately if i run it I see 
``ImportError: cannot import name run_delay
``
error, I've checked ``/usr/share/fence/fencing.py`` and can't find it there too.

If I remove "run_delay" from imported modules in "fence_pve" I run into next issues.
``
fence_pve --action=status --ip=192.168.122.2 --username=root@pam --password=secret  --plug=30000
Parse error: option --action not recognized
Please use '-h' for usage
``
Don't know if it's related, did I miss something?

OS: Debian Wheezy amd64

**Comment by marxsk** [comment]
Do you have fencing library in same version as fence_pve?

**Comment by xtavras** [comment]
sorry, my bad, the ``fencing.py`` comes with "fence-agents" package in Debian, no wonder is outdated.
