### ISSUE TITLE
Future request: Fix fence_agent without has port parameter.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#292]
Hi All,

When Pacemaker runs fence_agent that does not have a port parameter such as fence_mpath, the following parsing error occurs.

```
Sep 04 11:56:42 rh80-03 pacemaker-fenced    [4738] (operation_finished)         notice: fence_mpath_on_1:5153:stderr [ WARNING:root:Parse error: Ignoring unknown option 'port=rh80-03' ]
Sep 04 11:56:42 rh80-03 pacemaker-fenced    [4738] (operation_finished)         notice: fence_mpath_on_1:5153:stderr [  ]
Sep 04 11:56:42 rh80-03 pacemaker-fenced    [4738] (log_action)         warning: fence_mpath[5153] stderr: [ WARNING:root:Parse error: Ignoring unknown option 'port=rh80-03' ]
Sep 04 11:56:42 rh80-03 pacemaker-fenced    [4738] (log_action)         warning: fence_mpath[5153] stderr: [  ]
Sep 04 12:25:44 rh80-03 pacemaker-fenced    [4738] (operation_finished)         notice: fence_mpath_off_1:15366:stderr [ WARNING:root:Parse error: Ignoring unknown option 'port=rh80-04' ]
Sep 04 12:25:44 rh80-03 pacemaker-fenced    [4738] (operation_finished)         notice: fence_mpath_off_1:15366:stderr [  ]
Sep 04 12:25:44 rh80-03 pacemaker-fenced    [4738] (log_action)         warning: fence_mpath[15366] stderr: [ WARNING:root:Parse error: Ignoring unknown option 'port=rh80-04' ]
Sep 04 12:25:44 rh80-03 pacemaker-fenced    [4738] (log_action)         warning: fence_mpath[15366] stderr: [  ]
```

The problem can be avoided with the pcmk_host_argument parameter, but in the future, adding the port parameter and changing it to be handled in the same way as the key parameter will prevent user confusion.

This topic started with the next Bugzilla.
 - https://bugs.clusterlabs.org/show_bug.cgi?id=5403

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Additional comments:
* If both key and port are specified, key should take precedence (since the likely scenario is that pacemaker is sending port with the node name)
* key would no longer be required
* The expected use case for "port" (or possible with pcmk_host_argument="key" currently) is that the user will provide pcmk_host_map with node/key mappings

**Comment by oalbrigt** [comment]
For reference we just did the same for fence_openstack: https://github.com/ClusterLabs/fence-agents/pull/291/files

**Comment by oalbrigt** [comment]
Hideo: I might be able to make it next week if I'm not too busy.

**Comment by HideoYamauchi** [comment]
Hi oalbrigt,

I'm busy this month.
If I do the fix work, it will be next month.

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Hideo: I've already made a PR with the patch, so feel free to test it whenever you have the time.

**Comment by HideoYamauchi** [comment]
Hi oalbrigt,

> Hideo: I've already made a PR with the patch (it's referenced above), so feel free to test it whenever you have the time.

Great!

I will test your fix in the first half of next week.
I will also contact you with the results.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi oalbrigt,

I tested your fix because it had a little time.
Your fix works and fence_mpath works well even if you don't specify the key parameter.

Many thanks,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Great. Glad to hear it works.
