### ISSUE TITLE
Can't use "fence_pve" in pacemkaer

### ISSUE THREAD

**Issue by xtavras** [ClusterLabs/fence-agents#30]
Don't no if is right place to ask but I try anyway.

I have working "fence_pve" agent if I run it in terminal with arguments, but it doesn't work if I try to add it as stonith resource in pacemaker. It says some parameters like "passwd" or "login" does not exist (they are listed here [1]). 
some more info.
```
# stonith -L |grep pve

external/fence_pve
```
```
# stonith -t external/fence_pve -n
Failed: You have to enter fence address

Please use '-h' for usage

CRIT: external_get_confignames: 'fence_pve getconfignames' failed with rc 1

```

I'm using "fence_pve" from Debian testing which is identical with "fence_pve" in this repo.

[1] https://www.mankier.com/8/fence_pve#Stdin_Parameters

**Comment by marxsk** [comment]
Better place is mailing list at  users@clusterlabs.org

You have to enter arguments, this differ between various CLI utilities. With pcs it will be something like:

pcs stonith create myapc fence_apc_snmp params \
ipaddr="zapc.example.com" pcmk_host_map="z1.example.com:1;z2.example.com:2" \
login="apc" passwd="apc"
