### ISSUE TITLE
Switch ipmilan default from lan (version 1.5) to lanplus (IPMI version 2.0) interface

### ISSUE THREAD

**Issue by watologo1** [ClusterLabs/fence-agents#314]
Hi,

ipmilan uses the very deprecated lan (ipmitool -I lan) interface by default.
It can switch to lanplus via -P param:

man fence_ipmilan:
       -P, --lanplus
              Use Lanplus to improve security of connection (Default Value: 0)

Afaik all modern x86 service processors run (and need) via -I lanplus.
I am aware that this would be incompatible for current users who really still use -I lan.
They would have to use (I can send a patch) a compatibility param then:
       -d, --lan
              Use Lan (IPMI version 1.5). This is a compatibility param for very old IPMI service
              processors, still talking the old protocoll (Default Value: 0)

Thanks for any feedback,

    Thomas

**Comment by oalbrigt** [comment]
This is worth considering, so I'll have to check if we can change it or if it's been long enough since 1.5 was used that we can make lanplus default.
