### ISSUE TITLE
drac5 via ssh for newer dell servers

### ISSUE THREAD

**Issue by Klaas-** [ClusterLabs/fence-agents#315]
Hi,
I noticed the command prompt changed again for current dell idrac9 version:
iDRAC9 4.00.00.00 command prompt: "racadm>>"
iDRAC9 3.* command prompt: "/admin1->"

I also had to increase shell and power timeout.

Current working cli for drac9 4.*:
fence_drac5 --ssh --shell-timeout=30 --power-timeout=30 --command-prompt="racadm>>" --action=status

Greetings
Klaas

**Comment by oalbrigt** [comment]
Thank you for reporting this.

fence_redfish is the preferred agent for iDRAC9, but we might consider adding a note about this in the metadata of fence_drac5.

**Comment by Klaas-** [comment]
I have not yet got around to move the fencing to redfish, but it has been on my todo list for way too long :)
