### ISSUE TITLE
About the path to the log file

### ISSUE THREAD

**Issue by bd233** [ClusterLabs/fence-agents#327]
https://github.com/ClusterLabs/fence-agents/blob/8f1d620d9e0ca9331cbf801572da6c793e953a40/agents/aliyun/fence_aliyun.py#L27

I modified the log level here to INFO, but I didn't find the corresponding content in the /var/log/ message or /var/log/pacemaker.log file. Is it in other log files？

**Comment by oalbrigt** [comment]
It could be in /var/log/corosync.log (might be under /var/log/cluster depending on distro).

**Comment by bd233** [comment]
> It could be in /var/log/corosync.log (might be under /var/log/cluster depending on distro).

thx
