### ISSUE TITLE
AWS permissons

### ISSUE THREAD

**Issue by jadams-lg** [ClusterLabs/fence-agents#344]
While testing the AWS fencing mechanism we discovered that if you lock down the source IP in which the "reboot" is call from fence_aws for RHEL. Fencing errors with a timeout. While the command "aws ec2 reboot-instances --instance-ids i-blablah" works without issue. Thus the question is access to resource * required and source IP an issue when using fence_aws?

**Comment by oalbrigt** [comment]
It shouldnt bind to an IP, but maybe the aws command has better fallback code for cases like this.

The fence agent will try and get the status to confirm the node has been turned off/on (or off followed by on) or rebooted, so maybe that's causing the issue.

You could copy the agent to your home-directory and add a couple of `logger.error("TEST: <function/region info>")` in the code to try and identify where it fails.
