### ISSUE TITLE
Add Support for IMDSv2 for fence_aws 

### ISSUE THREAD

**Issue by davdunc** [ClusterLabs/fence-agents#362]
There is a reference implementation in the ec2-metadata query tool here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html

Last year, AWS released "IMDSv2" in an effort to protect customers against some potentially severe information leaks
related to accidentally proxying this local data to the network. Details
at https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

IMDSv2 makes use of a session-based protocol, requiring clients to first retrieve a time-limited session token, and then to include that token with subsequent requests.

Because the intended purpose of IMDSv2 is to provide an additional layer of defense against network abuses, customers utilizing it may choose to disable IMDSv1. Disabling IMDSv2 today causes fence_aws to fail.

**Comment by oalbrigt** [comment]
Thanks.

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/fence-agents/pull/366
https://github.com/ClusterLabs/resource-agents/pull/1578
