### ISSUE TITLE
[Feature] fence_kubevirt

### ISSUE THREAD

**Issue by dankenigsberg** [ClusterLabs/fence-agents#401]
It would be lovely if someone could implement `fence_kubevirt` which uses the [KubeVirt API](https://kubevirt.io/api-reference/) in order to fence a VM running on a KubeVirt cluster.

I would like to run something like
```
$ KUBECONFIG=~/.kube/config fence_kubevirt -n vm-name --namespace vm-namespace -o status
Status: ON
```

**Comment by nirarg** [comment]
You can find relevant PR:
https://github.com/ClusterLabs/fence-agents/pull/412
