### ISSUE TITLE
What is the second "get_power_status" param for? fence_apc

### ISSUE THREAD

**Issue by kwaping** [ClusterLabs/fence-agents#41]
I'm thinking the second "get_power_status" is not used, but also doesn't cause any issues. Is that correct? If it is used, how? I'm asking because I'm basing a new fence agent off of this code and want to fully understand what's going on.

[code in question](https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/apc/fence_apc.py#L251-L253)

**Comment by marxsk** [comment]
https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/lib/fencing.py.py#L759

Sometimes, if you query for status of an outlet, you receive all of them. In such case it makes sense to re-use same function also for 'list/list-status' actions.
