### ISSUE TITLE
[Question] About the log when using fence_scsi with watchdog service.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#482]
Hi All,

When fence_scsi is combined with the watchdog service, when the node is restarted, the following log will continue to be output from the watchdog service unless fence_scsi is started by pacemaker.

```
(snip)
ERROR:root:Failed: Cannot open file "/var/run/cluster.dev"

ERROR:root:No devices found
ERROR:root:Failed: Cannot open file "/var/run/cluster.dev"

ERROR:root:No devices found
ERROR:root:Failed: Cannot open file "/var/run/cluster.dev"

ERROR:root:No devices found
ERROR:root:Failed: Cannot open file "/var/run/cluster.dev"

ERROR:root:No devices found
ERROR:root:Failed: Cannot open file "/var/run/cluster.dev"

ERROR:root:No devices found
ERROR:root:Failed: Cannot open file "/var/run/cluster.dev"

ERROR:root:No devices found
ERROR:root:Failed: Cannot open file "/var/run/cluster.dev"
(snip)
```

This log is very noisy.

For example, when fence_scsi is started from the watchdog service, isn't it better to suppress logging as follows?

```
--- /usr/sbin/fence_scsi        2022-05-09 09:10:45.598157100 +0900
+++ /usr/share/cluster/fence_scsi_check 2022-05-09 09:25:44.872598600 +0900
@@ -275,7 +275,8 @@
        try:
                f = open(file_path, "r")
        except IOError:
-               fail_usage("Failed: Cannot open file \"" + file_path + "\"", fail)
+               if fail:
+                       fail_usage("Failed: Cannot open file \"" + file_path + "\"", fail)
                if not fail:
                        return None
        # get not empty lines from file
@@ -447,7 +448,7 @@
                logging.getLogger().setLevel(logging.DEBUG)
        devs = dev_read(fail=False)
        if not devs:
-               logging.error("No devices found")
+       #       logging.error("No devices found")
                return 0
        key = get_key(fail=False)
        if not key:
```

Or can this log be suppressed with better changes?

The same problem occurs with fence_mpath.

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Seems like we could do something like you're suggesting, and add similar functionality to the logging.error().

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment

> Seems like we could do something like you're suggesting, and add similar functionality to the logging.error().

Okay!
I think about the fix a bit.

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Maybe we should add an option like suppress-errors that can be set in the config file to avoid affecting users who might expect these.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment.

> Maybe we should add an option like suppress-errors that can be set in the config file to avoid affecting users who might expect these.

Okay! 
I would like to suppress problem logging when the option is set in /etc/sysconfig/stonith.

Many thanks,
Hideo Yamauchi.
