### ISSUE TITLE
Missing import in some agents

### ISSUE THREAD

**Issue by emesika** [ClusterLabs/fence-agents#485]
Hi 

Commit bf32059e26f6a7d019df0f7949ce66adf997bc21 added some logging to agents code but didn't add "import logging" where needed 
the following agents are affected : 

agents/apc/fence_apc.py 
agents/ilo_moonshot/fence_ilo_moonshot.py 
agents/lpar/fence_lpar.py

**Comment by oalbrigt** [comment]
Thanks.

Fix for fence_apc/fence_ilo_moonshot:
https://github.com/ClusterLabs/fence-agents/pull/486

fence_lpar has been changed to use fail_usage() instead.
