### ISSUE TITLE
fencing using qemu:///session does not show any vm

### ISSUE THREAD

**Issue by kk0nrad** [ClusterLabs/fence-agents#506]
hello, I have an issue, probablie due to the fact that I'm using vms that run in my qemu:///session instead of qmenu:///system

the host server has fence_virtd installed and running:

[root@firebird ~]# systemctl status fence_virtd
● fence_virtd.service - Fence-Virt system host daemon
     Loaded: loaded (/usr/lib/systemd/system/fence_virtd.service; enabled; vendor preset: disabled)
     Active: active (running) since Sat 2022-10-29 09:42:16 CEST; 43s ago
       Docs: man:fence_virtd(8)
             man:fence_virt.con(5)
    Process: 107008 ExecStart=/usr/sbin/fence_virtd $FENCE_VIRTD_ARGS (code=exited, status=0/SUCCESS)
   Main PID: 107009 (fence_virtd)
      Tasks: 1 (limit: 18829)
     Memory: 2.7M
        CPU: 45ms
     CGroup: /system.slice/fence_virtd.service
             └─ 107009 /usr/sbin/fence_virtd -w

Oct 29 09:42:16 firebird systemd[1]: Starting fence_virtd.service - Fence-Virt system host daemon...
Oct 29 09:42:16 firebird fence_virtd[107009]: fence_virtd starting.  Listener: multicast  Backend: libvirt
Oct 29 09:42:16 firebird systemd[1]: Started fence_virtd.service - Fence-Virt system host daemon.

I will use it with virbr0 interface.
the conf file looks like this:

backends {
	libvirt {
		uri = "qemu:///system";
	}

}

listeners {
	multicast {
		port = "1229";
		family = "ipv4";
		interface = "virbr0";
		address = "225.0.0.12";
		key_file = "/etc/cluster/fence_xvm.key";
	}

}

fence_virtd {
	module_path = "/usr/lib64/fence-virt/";
	backend = "libvirt";
	listener = "multicast";
}

[root@firebird ~]# md5sum /etc/cluster/fence_xvm.key
2299e9ffb448a1233dab3287adc47e4a  /etc/cluster/fence_xvm.key

I will attach one of the vm nodes (they are three in total, and they are identical)

[konrad@firebird ~]$ virsh list
 Id   Name              State
---------------------------------
 2    rocky8-ha-node2   running
 3    rocky8-ha-node3   running
 5    rocky8-ha-node1   running

[konrad@firebird ~]$ virsh dumpxml rocky8-ha-node1
<domain type='kvm' id='5'>
  <name>rocky8-ha-node1</name>
  <uuid>08f73903-6d62-411f-adff-84c62a9e8687</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://rockylinux.org/rocky/8"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit='KiB'>2097152</memory>
  <currentMemory unit='KiB'>2097152</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <os>
    <type arch='x86_64' machine='pc-q35-6.2'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state='off'/>
  </features>
  <cpu mode='host-passthrough' check='none' migratable='on'/>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' discard='unmap'/>
      <source file='/home/konrad/.local/share/libvirt/images/rocky8-ha-node1.qcow2' index='2'/>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu'/>
      <target dev='sda' bus='sata'/>
      <readonly/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0' model='qemu-xhci' ports='15'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'>
      <alias name='pcie.0'/>
    </controller>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <alias name='pci.1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='2' port='0x11'/>
      <alias name='pci.2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x12'/>
      <alias name='pci.3'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x13'/>
      <alias name='pci.4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x14'/>
      <alias name='pci.5'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='6' port='0x15'/>
      <alias name='pci.6'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x5'/>
    </controller>
    <controller type='pci' index='7' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='7' port='0x16'/>
      <alias name='pci.7'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x6'/>
    </controller>
    <controller type='pci' index='8' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='8' port='0x17'/>
      <alias name='pci.8'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x7'/>
    </controller>
    <controller type='pci' index='9' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='9' port='0x18'/>
      <alias name='pci.9'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='10' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='10' port='0x19'/>
      <alias name='pci.10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x1'/>
    </controller>
    <controller type='pci' index='11' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='11' port='0x1a'/>
      <alias name='pci.11'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x2'/>
    </controller>
    <controller type='pci' index='12' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='12' port='0x1b'/>
      <alias name='pci.12'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x3'/>
    </controller>
    <controller type='pci' index='13' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='13' port='0x1c'/>
      <alias name='pci.13'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x4'/>
    </controller>
    <controller type='pci' index='14' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='14' port='0x1d'/>
      <alias name='pci.14'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x5'/>
    </controller>
    <controller type='sata' index='0'>
      <alias name='ide'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <alias name='virtio-serial0'/>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <interface type='bridge'>
      <mac address='52:54:00:c6:dc:71'/>
      <source bridge='virbr0'/>
      <target dev='tap0'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
    <serial type='pty'>
      <source path='/dev/pts/0'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
      <alias name='serial0'/>
    </serial>
    <console type='pty' tty='/dev/pts/0'>
      <source path='/dev/pts/0'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <channel type='unix'>
      <source mode='bind' path='/home/konrad/.config/libvirt/qemu/channel/target/domain-5-rocky8-ha-node1/org.qemu.guest_agent.0'/>
      <target type='virtio' name='org.qemu.guest_agent.0' state='connected'/>
      <alias name='channel0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0' state='disconnected'/>
      <alias name='channel1'/>
      <address type='virtio-serial' controller='0' bus='0' port='2'/>
    </channel>
    <input type='tablet' bus='usb'>
      <alias name='input0'/>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'>
      <alias name='input1'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input2'/>
    </input>
    <graphics type='spice' port='5900' autoport='yes' listen='127.0.0.1'>
      <listen type='address' address='127.0.0.1'/>
      <image compression='off'/>
    </graphics>
    <sound model='ich9'>
      <alias name='sound0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1b' function='0x0'/>
    </sound>
    <audio id='1' type='spice'/>
    <video>
      <model type='virtio' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <alias name='redir0'/>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <alias name='redir1'/>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </memballoon>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
      <alias name='rng0'/>
      <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
    </rng>
  </devices>
  <seclabel type='dynamic' model='selinux' relabel='yes'>
    <label>unconfined_u:unconfined_r:svirt_t:s0:c99,c908</label>
    <imagelabel>unconfined_u:object_r:svirt_image_t:s0:c99,c908</imagelabel>
  </seclabel>
</domain>

the guest servers have fence-virt installed

[root@rocky8-ha-node1 ~]# rpm -qa|grep fence
fence-virt-1.0.0-2.el8.x86_64
[root@rocky8-ha-node1 ~]# 

the key file is the same one:
[root@rocky8-ha-node1 ~]#  md5sum /etc/cluster/fence_xvm.key
2299e9ffb448a1233dab3287adc47e4a  /etc/cluster/fence_xvm.key
[root@rocky8-ha-node1 ~]# 

but I dont see any of the VMs using fence_xvm -o list

from host:
[root@firebird ~]# fence_xvm -o list

from guests:
[root@rocky8-ha-node1 ~]# fence_xvm -o list
[root@rocky8-ha-node1 ~]# 

[root@rocky8-ha-node2 ~]# fence_xvm -o list
[root@rocky8-ha-node2 ~]# 

[root@rocky8-ha-node3 ~]# fence_xvm -o list
[root@rocky8-ha-node3 ~]# 

is this related to the fact that the VMs are in qemu:///session environment?
[root@firebird ~]# virsh list
 Id   Name   State
--------------------

[root@firebird ~]# 
[konrad@firebird ~]$ virsh list
 Id   Name              State
---------------------------------
 2    rocky8-ha-node2   running
 3    rocky8-ha-node3   running
 5    rocky8-ha-node1   running

[konrad@firebird ~]$ 

thanks

**Comment by fabbione** [comment]
As discussed with the report via chat, the solution to this problem is to use per-user uri. For example:

uri = "qemu:///session?socket=/run/user/1000/libvirt/virtqemud-sock"

where 1000 is the user ID.

I am not closing this issue as is, as those information could be better documented in fence_virt.conf.5. Perhaps a link to the libvirt uri docs might be useful.

**Comment by fabbione** [comment]
The rest of the discussion was in Italian anyway ;)

I think we want to make sure that the user is aware that fence-virtd will accept all libvirt uris (as they are passed pristine to the virtAPI) with a link to the libvirt doc, and perhaps add a NOTE: if the VMs are running as non root user, you need to use paths to user sockets (example: qemu:///session?socket=/run/user/<UID>/libvirt/virtqemud-sock)

**Comment by oalbrigt** [comment]
Sounds good.
