### ISSUE TITLE
Error: No stonith agents available. Do you have fence agents installed?

### ISSUE THREAD

**Issue by edgarbrignoni** [ClusterLabs/fence-agents#524]
I install fence_aws (aws_fence) on both ec2-instances...previous to that I manage to setup two nodes clusters using EBS multi-attach setup, but before creating the GFS2 volume, I need to setup a fence. Since it is AWS, I install the latest fence-agents-aws, but when trying to setup fencing, I get the error.

`sudo yum install fence-agents-aws.x86_64 -y`

Package fence-agents-aws-4.2.1-24.amzn2.0.3.x86_64 already installed and latest version
Nothing to do

`sudo pcs stonith list`

Error: No stonith agents available. Do you have fence agents installed?

Can someone assist?

Kind Regards,

Edgar Brignoni

**Comment by oalbrigt** [comment]
This sounds like the agent might be installed in non-standard location. `pcs stonith list` usually looks for fence_* in /usr/sbin/.

Try running `rpm -ql fence-agents-aws` and see where it's located. You can also try running it manually `fence_aws -o metadata` to see if there's any errors or it outputs metadata like it should.

You should report it to the distro you're running, so they can fix it.

**Comment by edgarbrignoni** [comment]
Thanks @oalbrigt for your support on this issue. You were able to guide me in the right direction. Here are some of the results after running the commands.

```
[ec2-user@ma-host-1 html]$ rpm -ql fence-agents-aws
/usr/sbin/fence_aws
/usr/share/man/man8/fence_aws.8.gz
[ec2-user@ma-host-1 html]$ fence_aws -o metadata
Traceback (most recent call last):
  File "/usr/sbin/fence_aws", line 10, in <module>
    import boto3
ImportError: No module named boto3
```
I then proceeded to install `boto3` on the Amazon Linux 2 instances, but first I needed pip.

```
sudo yum install python-pip -y
...
sudo pip install boto3
...
[root@ma-host-2 /]# sudo pcs stonith list
fence_aws - Fence agent for AWS (Amazon Web Services)
```
I try using python3.X to install boto3 with `pip3 install boto3` but unfortunately that did not work. Still, I was able to do what I needed to do, then I worry about using pip3 since I believe pytho2.X is no longer going to be supported.

Thanks again,

Edgar Brignoni

**Comment by oalbrigt** [comment]
It might be available as python3-boto3, but it's a bit strange that it doesnt depend on it.
