### ISSUE TITLE
[Question] About the ipmitool_timeout parameter of fence_ipmilan.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#525]
Hi all,

The ipmitool_timeout parameter of fence_ipmilan is set to 2s by default, but looking at the man page of ipmitool, 
I think it is necessary to specify 1s if the lanplas parameter (-P or --lanplus parameter of fence_ipmilan) is specified.

```
       -N <sec>
              Specify nr. of seconds between retransmissions of lan/lanplus messages.  Defaults are 2 seconds for lan and 1 second  for  lanplus  interfaces.
              Command raw uses fixed value of 15 seconds.  Command sol uses fixed value of 1 second.
```

What do you think?

Best Regrards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
This should be fine.

It's probably just got decreased default as newer devices (lanplus) are less likely to fail within 1s, but it's fine to have it at 2s, and changing it to 1s could even cause issues for some users who got slower lanplus devices.

The agent supports changing the value via --ipmitool-timeout, so users can lower it if they want.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Thanks for your comment.
In the case of lanplus, I understand that it will match the 2s.

Many Thanks,
Hideo Yamauchi.
