### ISSUE TITLE
'Connection timed out' on fence_sbd --action=reboot

### ISSUE THREAD

**Issue by underoll** [ClusterLabs/fence-agents#60]
`fence_sbd --devices=... --plug=... --verbose --action=reboot` fails each time with 'Connection timed out'

**Comment by marxsk** [comment]
Please try to contact Adrian who wrote this fence agent:

Adrian Vondendriesch <adrian.vondendriesch@credativ.de>

**Comment by vvidic** [comment]
Fixed in pull request #73

**Comment by disco-stu** [comment]
Please merge pull request #73. The bug he fixed is responsible for the "time out" error underoll mentioned.

**Comment by marxsk** [comment]
Pull request #73  was merged
