### ISSUE TITLE
fence_scsi action list ?

### ISSUE THREAD

**Issue by rmontagne** [ClusterLabs/fence-agents#62]
Hi,

Does fence_scsi implements list action ? Because when i tried tu use it on multi-nodes fencing already failed.

Thanks for your responses.

Regards.

**Comment by marxsk** [comment]
Hi,

no, list-action is not implemented for fence_scsi. Mostly because fence agents do not know about other nodes, so it does not see which devices are suitable for fencing (local vs remote)

**Comment by rmontagne** [comment]
Hi, thanks for your quick response, i don't understand why i have already this messages Failed: Cannot open file "/var/run/cluster/fence_scsi.key", 

Can you tell me when, the node status are set ?

Thanks.

**Comment by marxsk** [comment]
Very likely, you forgot to do 'unfence' or SELinux is blocking creating of this file. Take a look at one of tutorials that are around.

**Comment by rmontagne** [comment]
I follow the guide, but i don't understant why, fence already failing.

SELINUX=disabled

pcs stonith create iscsi-stonith-device fence_scsi devices="/dev/disk/by-id/scsi-1494554000000000094ce82fe1024d4d11a7ed08bde9b91e9" meta provides=unfencing

What is wrong ?

**Comment by rmontagne** [comment]
Resource: iscsi-stonith-device (class=stonith type=fence_scsi)
  Attributes: devices=/dev/disk/by-id/scsi-1494554000000000094ce82fe1024d4d11a7ed08bde9b91e9 
  Meta Attrs: provides=unfencing 
  Operations: monitor interval=60s (iscsi-stonith-device-monitor-interval-60s)

**Comment by marxsk** [comment]
Command looks fine, you can try to test fence_scsi directly (without cluster; just test status/unfence/status/fence/status/unfence) and check if the file will be created or not.

Also make sure that you are not running too old version.

**Comment by rmontagne** [comment]
I mount a fresh cluster of 4 nodes, and i already have the problem.

![capture d ecran 2016-03-10 a 17 15 59](https://cloud.githubusercontent.com/assets/3686578/13675876/da0a6e14-e6e3-11e5-8b81-39d895dbbeb2.png)

**Comment by rmontagne** [comment]
[root@front1 svadmin]# fence_scsi -n front1 --action=status
Status: ON
[root@front1 svadmin]# fence_scsi -n front1 --action=on
Success: Powered ON
[root@front1 svadmin]# fence_scsi -n front1 --action=status
Status: ON

File has been create, i must do this action on all nodes ?

**Comment by marxsk** [comment]
Hi,

if fence agent returns 'ON' then file was there before. But this looks like integration problem, not an issue in fence agent. Please, use cluster-user list for such issue: http://clusterlabs.org/wiki/Mailing_lists

**Comment by rmontagne** [comment]
Thanks for your time.

**Comment by kuwv** [comment]
This issue should be reopened as the SELinux policy is not working correcly.

1. To reproduce ensure that SELinux enabled
$ sestatus

2. Create a fence_scsi instance
$ pcs property set maintenance-mode=true
$ pcs stonith create scsi-shooter fence_scsi devices="/dev/disk/by-id/wwn-<id>" meta provides=unfencing

3. Initiate the cluster LVM daemons
$ pcs resource create dlm ocf:pacemaker:controld op monitor interval=30s on-fail=fence clone interleave=true ordered=true 
$ pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=fence clone interleave=true ordered=true 

$ pcs constraint order start dlm-clone then clvmd-clone
$ pcs constraint colocation add clvmd-clone with dlm-clone

$ pcs property set maintenance-mode=false
$ watch pcs status resources

4. Verify that you're having a bad day
$ tail -50 /var/log/messages

**Comment by marxsk** [comment]
@kuwv Thanks for a reproducer, I will work on this issue next week together with SELinux guys.
