### ISSUE TITLE
RHEL6 branches mismatch with git.fedorahosted.org/fence-agents.git (follow-up of #64)

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/fence-agents#66]
Unfortunately, it seems that GitHub migration killed integrity.

```
$ git clone https://github.com/ClusterLabs/fence-agents
$ cd fence-agents
$ git remote add fh git://git.fedorahosted.org/fence-agents.git
$ git fetch origin
$ git fetch fh
$ C=$(git merge-base origin/RHEL6 fh/RHEL6)
$ git log -n1 --decorate=full --simplify-by-decoration "${C}"
commit 5a518f3cb382c2711bd027916164c7ac45ab3e3e (tag: v3.1.5)
Author: Marek 'marx' Grac <mgrac@redhat.com>
Date:   Fri Jul 8 09:54:42 2011 +0200

    fence_drac5: Incorrect output of 'list' operation on Drac 5
    
    Previously (due to other bug) fence agents operation 'list' was not
    working properly. After fixing that issue, drac5 returned empty line
    instead of N/A as an output for 'list'. This happends because fencing
    library does not have support for situations when for one fence agents
    there are fence devices that supports / not supports 'list' option.
    
    Resolves: rhbz#718194 (regression introduced by previous patch)
```

Thus, the newest commit these two variants of RHEL6 branch have in common
is almost 5 years ago (long before migration to GitHub, IIUIC) when
fence-agents-3.1.5 was released.

It is expected that the two remotes match on all the branches up
to the point fedorahosted.org was abandoned as the current unhealthy
state results in "all hosting sites are equal (up to the point of
abandonment) but some are more equal".

**Comment by marxsk** [comment]
RHEL6/RHEL7 are non-official branches that attempts to provide version that can be executed on given platforms. Solving any issues with fedorahosted.org is not worth investing time. Sorry

**Comment by jnpkrn** [comment]
My point was mainly that code hosting migrations should be handle with due care/responsibly. For instance, some commit references applicable for RHEL6 branch at fedorahosted.org hosting cannot be resolved as commits at GitHub.  Can you, at the very least, mirror fedorahosted.org branches affected by this deliberate inconsistency as branches akin to fh-mirror-RHEL6? That would reliably preserve the commit hashes even if fedorahosted.org repo hosting is terminated.
