### ISSUE TITLE
rcd_serial from master in RHEL7?

### ISSUE THREAD

**Issue by sammcj** [ClusterLabs/fence-agents#72]
What would be the recommended / 'best' way to use the fence_rcd_serial agent I wrote in RHEL/CentOS 7?

It was merged into master 7 months ago but it looks like the RHEL7 branch still doesn't contain it which is what I'm assuming red hat would use to build their package from?

https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/rcd_serial/fence_rcd_serial.py

**Comment by marxsk** [comment]
Hi,

fence_rcd_serial will not be part of RHEL7 branch that tracks fence agents as they are distributed in RHEL 7.x. If fence agent is part of RHEL 7.x it has to be supported and this is not a type of hardware that you wish to support officialy. 

On RHEL/CentOs 7 it might be the easiest way to take 'master' branch. It should works without any issues.
