### ISSUE TITLE
Will the fedorahosted site continue to be maintained for tarballs?

### ISSUE THREAD

**Issue by nacc** [ClusterLabs/fence-agents#83]
Debian (and Ubuntu) use
https://fedorahosted.org/releases/f/e/fence-agents/
to determine the upstream releases. That location also contains .bz2 and .xz files (more than github's releases page). Will the fedorahosted.org page stay current going forward?

**Comment by marxsk** [comment]
Hi,

very likely yes because it is part of release scripts. But feel free to bind to tags here on github
