### ISSUE TITLE
fence_vbox line 34 log_expect() missing "options" for first argument.

### ISSUE THREAD

**Issue by mdiehn** [ClusterLabs/fence-agents#89]
amy and pat are two of my five VirtualBox demo VMs.
yttrium is my workstation, hosting them

Issue this command:
    [root@amy ~]# ./fence_vbox --plug=pat --action=status \
    >                          --ip=yttrium --ssh --username=mdiehn \
    >                           --identity-file=/root/.ssh/id_rsa-to-mdiehn_yttrium

Expected result:
    Status: ON

Actual result:
    Traceback (most recent call last):
      File "./fence_vbox", line 113, in <module>
        main()
      File "./fence_vbox", line 108, in main
        result = fence_action(conn, options, set_power_status, get_power_status, get_outlets_status)
      File "/usr/share/fence/fencing.py", line 964, in fence_action
        status = get_multi_power_fn(tn, options, get_power_fn)
      File "/usr/share/fence/fencing.py", line 871, in get_multi_power_fn
        plug_status = get_power_fn(tn, options)
      File "./fence_vbox", line 59, in get_power_status
        _invoke(conn, options, "list", "runningvms")
      File "./fence_vbox", line 34, in _invoke
        conn.log_expect(options["--command-prompt"], int(options["--shell-timeout"]))
    TypeError: log_expect() takes exactly 4 arguments (3 given)

Cause:

Line 34 of fence_vbox is missing the first argument, which I infer should be "options." Easy mistake to make seeing that the next two arguments are "options[blah, blah]", and "options[nag, nag]":

Is like this:
    conn.log_expect(options["--command-prompt"], int(options["--shell-timeout"]))

Should be like this:
    conn.log_expect(options, options["--command-prompt"], int(options["--shell-timeout"]))

**Comment by oalbrigt** [comment]
This seems to be caused by the master version of fence_vbox with some older version of the fencing libraries.

Try the following from your github cloned directory:
PYTHONPATH=fence/agents/lib python fence/agents/vbox/fence_vbox ...

**Comment by marxsk** [comment]
@oalbrigt is right that is using older version of the fencing library, very likely one installed from packages.

**Comment by kladiv** [comment]
@oalbrigt Hi, issue still present.
I compiled master branch **fence_vbox** on a RHEL7 and i got same error

**Comment by oalbrigt** [comment]
@kladiv: make sure to use PYTHONPATH to point to the master branch version of the fencing library like shown above.

**Comment by kladiv** [comment]
@oalbrigt Scenario is:
1.  fence-agents installed from standard repository (no fence_vbox present)
2. so i compiled the fence agents from master branch, autogen + configure + make
3. copy only fence_vbox into /sbin path of server
PYTHONPATH env should be used during compiling or at the end too?

**Comment by oalbrigt** [comment]
Run the following 2 commands to install the library in /usr/local prefix without affecting other agents you might have installed:
./configure --prefix=/usr/local --with-fenceagentslibdir=/usr/local/share/fence --with-agents=vbox
make && make install

And rm /sbin/fence_vbox so you dont run the one that doesnt use the correct libraries.
